---
   - sysctl:
      name: net.ipv6.conf.all.disable_ipv6
      value: 1
      sysctl_set: yes
      state: present
      reload: yes
   - sysctl:
      name: net.ipv6.conf.default.disable_ipv6
      value: 1
      sysctl_set: yes
      state: present
      reload: yes
   - sysctl:
      name: net.ipv6.conf.lo.disable_ipv6
      value: 1
      sysctl_set: yes
      state: present
      reload: yes
   - sysctl:
      name: net.ipv6.conf.eth0.disable_ipv6
      value: 1
      sysctl_set: yes
      state: present
      reload: yes
