---
   - package: name=nginx state=installed
   - service: name=nginx state=started
   - template:
      src: templates/etc/nginx/nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      owner: sys_web
      group: root
   - template:
      src: templates/etc/ntp.conf.j2
      dest: /etc/ntp.conf
      owner: root
      group: root
   - group:
      name: sys
   - user:
      name: sys_web
      shell: /bin/false
      group: sys
      uid: 2001
      state: present
   - file:
      path: /srv/web
      state: directory
      mode: 0755
      owner: sys_web
      group: sys
   - template:
      src: templates/srv/web/index.html.j2
      dest: /srv/web/index.html
      owner: sys_web
      group: sys

      