---
 - hosts: webservers
   remote_user: root
   tasks:
   - include_vars: defaults/main.yml
   - package: name=nginx state=installed
   - package: name=nscd state=installed
   - template:
      src: templates/etc/nginx/nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      owner: sys_web
      group: root
   - template:
      src: templates/etc/ntp.conf.j2
      dest: /etc/ntp.conf
      owner: root
      group: root
   - group:
      name: sys
   - user:
      name: sys_web
      shell: /bin/false
      group: sys
      uid: 2001
      state: present
   - file:
      path: /srv/web
      state: directory
      mode: 0755
      owner: sys_web
      group: sys
   - template:
      src: templates/srv/web/index.html.j2
      dest: /srv/web/index.html
      owner: sys_web
      group: sys

   - service: name=nginx state=started
   - service: name=cron state=stopped
   - service: name=ntp state=started
   - service: name=nscd state=started

   - sysctl:
      name: net.ipv6.conf.all.disable_ipv6
      value: 1
      sysctl_set: yes
      state: present
      reload: yes
   - sysctl:
      name: net.ipv6.conf.default.disable_ipv6
      value: 1
      sysctl_set: yes
      state: present
      reload: yes
   - sysctl:
      name: net.ipv6.conf.lo.disable_ipv6
      value: 1
      sysctl_set: yes
      state: present
      reload: yes
   - sysctl:
      name: net.ipv6.conf.eth0.disable_ipv6
      value: 1
      sysctl_set: yes
      state: present
      reload: yes

