---
- site: internal
- pass_rules:
    infra:
      order: "OPS001"
      from:
        range:
          - 172.16.2.0/24
      to:
        range:
          - 172.16.1.0/24
        ports:
          - 22
          - 80
